const actionTypes = {
  SET_IMAGE_FILES: 'SET_IMAGE_FILES',
  SET_SEL_DRAW_IMAGE_INDEX: 'SET_SEL_DRAW_IMAGE_INDEX',
  SET_IMAGE_SIZES: 'SET_IMAGE_SIZES',
  SET_SEL_IMAGE_INDEXES: 'SET_SEL_IMAGE_INDEXES',
  SET_DRAW_STATUS: 'SET_DRAW_STATUS',
  SET_SEL_SHPAE_TYPE: 'SET_SEL_SHPAE_TYPE',
  SET_LABELBOX_STATUS: 'SET_LABELBOX_STATUS',
  SET_XML_PREVIEW_BOX_STATUS: 'SET_XML_PREVIEW_BOX_STATUS',
  SET_URL_BOX_STATUS: 'SET_URL_BOX_STATUS',
  SET_CURRENT_SHAPE: 'SET_CURRENT_SHAPE',
  SET_SHAPES: 'SET_SHAPES',
  SET_SEL_SHAPE_INDEX: 'SET_SEL_SHAPE_INDEX',
  SET_LABEL_TYPES: 'SET_LABEL_TYPES',
  SET_SEL_LABEL_TYPE: 'SET_SEL_LABEL_TYPE',
  DELETE_SEL_SHAPE: 'DELETE_SEL_SHAPE',
  DELETE_ALL_SHAPES: 'DELETE_ALL_SHAPES'
};

export default actionTypes;
